import { Timestamp } from 'firebase-admin/firestore';

/**
 * Represents a log entry created each time a course's average ratings
 * are updated due to a processed review.
 */
export interface CourseRatingUpdateLog {
  id?: string; // Auto-generated by Firestore
  courseId: string; // ID of the course whose ratings were updated
  triggeringReviewId: string; // ID of the review that triggered this update
  triggeringUserId: string | null; // ID of the user who submitted the review (null if unknown/error)
  timestamp: Timestamp; // Firestore server timestamp of when the update occurred
  
  // Optional: Snapshot of the ratings from the triggering review for context
  reviewRatings: {
    overall: number;
    cost: number;
    condition: number;
    hilliness: number;
    distance: number;
    weighted: number; // The calculated weighted rating from the review
  };
} 